Document: shadow
Title: Debian shadow Manual
Author: <insert document author here>
Abstract: This manual describes what shadow is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/shadow/shadow.sgml.gz

Format: postscript
Files: /usr/share/doc/shadow/shadow.ps.gz

Format: text
Files: /usr/share/doc/shadow/shadow.text.gz

Format: HTML
Index: /usr/share/doc/shadow/html/index.html
Files: /usr/share/doc/shadow/html/*.html
